In [17]:
import tensorflow as tf
import numpy
import pandas as pd 
from tensorflow.keras import layers 

from numpy import random
# data = pd.read_csv('original.txt', sep='\t')
# types = pd.read_csv('types.txt', sep='\t')

# from numpy import genfromtxt
# my_data = genfromtxt('raw.txt', delimiter='\t',names=True)
# types = genfromtxt('types.txt',delimiter='\t',dtype="unicode")


# raw working 
data = pd.read_csv('raw.txt', sep='\t')
types = pd.read_csv('types-numeric.txt', sep='\t')
labels = pd.read_csv('types-labels.txt', sep='\t')


In [18]:
random.seed(69)
ii = numpy.random.rand(len(data)) < 0.7 

np_data = data.values
np_types = types.values
np_labels = labels.values

train = np_data[ii]
test = np_data[~ii]

train_types = np_types[ii]
test_types = np_types[~ii]

train_labels = np_labels[ii]
test_labels = np_labels[~ii] 

r_train_types = train_types.ravel()
r_test_types = test_types.ravel()

r_train_labels = train_labels.ravel()
r_test_labels = test_labels.ravel()



In [19]:
# random forest baseline 
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf = rf.fit(train, r_train_labels)
rf

y_pred=rf.predict(test)


In [20]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
# Model Accuracy, how often is the classifier correct
print("Accuracy: ", metrics.accuracy_score(r_test_labels, y_pred))

yhat = confusion_matrix(r_test_labels, y_pred,)
print(yhat)


y_true = pd.Series(r_test_labels)
y_pred = pd.Series(y_pred)

pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

('Accuracy: ', 0.9537037037037037)
[[128   4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1 372   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2  10   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   0 152   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 24   3   0   5  33   0   0   0   0   0   0   0   0   0   1   0   0]
 [  1   1   0   0   0 154   0   0   0   0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0  28   1   0   0   0   0   0   0   0   0   1]
 [  1   1   0   0   0   0   1 175   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0 118   0   0   0   0   1   0   0   0]
 [  1   7   0   0   0   1   0   0   0 157   1   0   0   0   1   0   5]
 [  0   0   0   0   0   0   0   0   0   0 140   0   0   0   0   0   4]
 [  0   0   0   0   0   1   0   1   0   2   0  39   0   0   6   1   0]
 [  0   2   0   0   0   0   0   0   0   0   0   0 168   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 

Predicted  blca  brca  chol  coad  esca  hnsc  kich  kirc  lich  luad   ov  \
True                                                                         
blca        128     4     0     0     0     0     0     0     0     0    0   
brca          1   372     0     0     0     0     0     0     0     0    0   
chol          0     2    10     0     0     0     0     0     0     0    0   
coad          0     2     0   152     0     0     0     0     0     0    0   
esca         24     3     0     5    33     0     0     0     0     0    0   
hnsc          1     1     0     0     0   154     0     0     0     0    0   
kich          0     0     0     0     0     0    28     1     0     0    0   
kirc          1     1     0     0     0     0     1   175     0     0    0   
lich          0     0     0     0     1     0     0     0   118     0    0   
luad          1     7     0     0     0     1     0     0     0   157    1   
ov            0     0     0     0     0     0     0     0     0     0  140   
paad          0     0     0     0     0     1     0     1     0     2    0   
prad          0     2     0     0     0     0     0     0     0     0    0   
skcm          0     0     0     0     0     0     0     0     0     0    0   
stad          1     0     0     8     0     1     0     0     0     3    0   
thca          0     1     0     0     0     0     0     0     0     1    0   
ucec          0     7     0     0     0     0     0     0     0     1    0   
All         157   402    10   165    34   157    29   177   118   164  141   

Predicted  paad  prad  skcm  stad  thca  ucec   All  
True                                                 
blca          0     0     0     0     0     0   132  
brca          0     0     0     0     0     0   373  
chol          0     0     0     0     0     0    12  
coad          0     0     0     0     0     0   154  
esca          0     0     0     1     0     0    66  
hnsc          0     0     0     0     0     1   157  
kich          0     0     0     0     0     1    30  
kirc          0     0     0     0     0     0   178  
lich          0     0     1     0     0     0   120  
luad          0     0     0     1     0     5   173  
ov            0     0     0     0     0     4   144  
paad         39     0     0     6     1     0    50  
prad          0   168     0     0     0     0   170  
skcm          0     0   123     0     0     0   123  
stad          1     1     0   131     0     0   146  
thca          0     0     0     0   167     0   169  
ucec          0     0     0     0     0   171   179  
All          40   169   124   139   168   182  2376

In [21]:
from sklearn.neural_network import MLPClassifier 

clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf = clf.fit(train, r_train_labels)   

nnet_pred = clf.predict(test)

nnet_cm = confusion_matrix(r_test_labels, nnet_pred)
print(nnet_cm)

y_true = pd.Series(r_test_labels)
y_pred = pd.Series(nnet_pred)

pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

print("Accuracy: ", metrics.accuracy_score(r_test_labels, nnet_pred))

[[  0 132   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 373   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 154   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  66   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 157   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 178   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 120   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 173   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  50   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 170   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 123   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 

In [47]:
# model = tf.keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
# model.add(layers.Dense(64, activation='relu'))
# model.add(layers.Dense(64, activation='relu'))

# softmax with 17 output units; one for each class label 
# model.add(layers.Dense(17, activation='softmax'))

In [44]:
# One hot encoding for keras model 

from tensorflow.keras.utils import to_categorical
encoded_train = to_categorical(r_train_types)
encoded_test = to_categorical(r_test_types)


In [53]:
model = tf.keras.Sequential()

#model.add(layers.Dense(64, input_shape=(2403,)))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
# model.add(layers.Dense(64, activation='sigmoid'))

# softmax with 17 output units; one for each class label 
model.add(layers.Dense(17, activation='softmax'))

model.compile(optimizer=tf.train.RMSPropOptimizer(0.01),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
# setup model training 
# model.compile(optimizer=tf.train.AdamOptimizer(0.01),
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])
# Configure a model for categorical classification.
# model.compile(optimizer=tf.train.RMSPropOptimizer(0.01),
#               loss=tf.keras.losses.categorical_crossentropy,
#               metrics=[tf.keras.metrics.categorical_accuracy])

In [54]:

# train! 
# epochs is how many times you go through training set
# batch_size is the number of samples to propogate at once

model.fit(train, encoded_train, epochs=10, batch_size=32)


Epoch 1/10
5574/5574 [==============================] - 1s 262us/step - loss: 15.4588 - acc: 0.0409
Epoch 2/10
5574/5574 [==============================] - 1s 161us/step - loss: 15.4588 - acc: 0.0409
Epoch 3/10
5574/5574 [==============================] - 1s 161us/step - loss: 15.4588 - acc: 0.0409
Epoch 4/10
5574/5574 [==============================] - 1s 162us/step - loss: 15.4588 - acc: 0.0409
Epoch 5/10
5574/5574 [==============================] - 1s 181us/step - loss: 15.4588 - acc: 0.0409
Epoch 6/10
5574/5574 [==============================] - 1s 184us/step - loss: 15.4588 - acc: 0.0409
Epoch 7/10
5574/5574 [==============================] - 1s 162us/step - loss: 15.4588 - acc: 0.0409
Epoch 8/10
5574/5574 [==============================] - 1s 161us/step - loss: 15.4588 - acc: 0.0409
Epoch 9/10
5574/5574 [==============================] - 1s 164us/step - loss: 15.4588 - acc: 0.0409
Epoch 10/10
5574/5574 [==============================] - 1s 188us/step - loss: 15.4588 - acc: 0.0409

In [55]:
ynew = model.predict_classes(test)


In [56]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

nnyhat = confusion_matrix(test_types, ynew)
print(nnyhat)
print("Accuracy: ", metrics.accuracy_score(r_test_types, ynew))
# for i in range(len(r_test_labels)):
#     print("X=%s, Predicted=%s" % (r_test_labels[i], ynew[i]))
    

[[  0   0   0   0  68   0   7  48   0   0   0  20   0   1   0   0   0]
 [  0   0   0   0   0  63  48  17   0   0   0   4   0   0   0   0   0]
 [  0   0   1   0   0  25 318  10   0   0   0  19   0   0   0   0   0]
 [  0   0   0   0   0   5   5   0   0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   8 130  16   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  24  35   6   0   0   0   1   0   0   0   0   0]
 [  0   0   0   0   0  58  76   5   0   0   0  18   0   0   0   0   0]
 [  0   0   0   0   0   0  20   0   0   0   0  10   0   0   0   0   0]
 [  0   0   0   0   0   2 175   0   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  24  88   2   0   0   0   1   0   2   3   0   0]
 [  0   1   0   0   0  63  95  11   0   0   0   3   0   0   0   0   0]
 [  0   0   0   0   0   1  55 114   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  40  86  20   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1  10 113  14   0   0   0  30   0   0   0   0   1]
 [  0 