In [1]:
import tensorflow as tf
import numpy
import pandas as pd 
from tensorflow.keras import layers 

from numpy import random
# data = pd.read_csv('original.txt', sep='\t')
# types = pd.read_csv('types.txt', sep='\t')

# from numpy import genfromtxt
# my_data = genfromtxt('raw.txt', delimiter='\t',names=True)
# types = genfromtxt('types.txt',delimiter='\t',dtype="unicode")


# raw working 
data = pd.read_csv('raw.txt', sep='\t')
types = pd.read_csv('types-numeric.txt', sep='\t')
labels = pd.read_csv('types-labels.txt', sep='\t')


In [2]:
random.seed(69)
ii = numpy.random.rand(len(data)) < 0.7 

np_data = data.values
np_types = types.values
np_labels = labels.values

train = np_data[ii]
test = np_data[~ii]

train_types = np_types[ii]
test_types = np_types[~ii]

train_labels = np_labels[ii]
test_labels = np_labels[~ii] 

r_train_types = train_types.ravel()
r_test_types = test_types.ravel()

r_train_labels = train_labels.ravel()
r_test_labels = test_labels.ravel()



In [19]:
# random forest baseline 
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf = rf.fit(train, r_train_labels)
rf

y_pred=rf.predict(test)


In [20]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
# Model Accuracy, how often is the classifier correct
print("Accuracy: ", metrics.accuracy_score(r_test_labels, y_pred))

yhat = confusion_matrix(r_test_labels, y_pred,)
print(yhat)


y_true = pd.Series(r_test_labels)
y_pred = pd.Series(y_pred)

pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

('Accuracy: ', 0.9537037037037037)
[[128   4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1 372   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2  10   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   0 152   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 24   3   0   5  33   0   0   0   0   0   0   0   0   0   1   0   0]
 [  1   1   0   0   0 154   0   0   0   0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0  28   1   0   0   0   0   0   0   0   0   1]
 [  1   1   0   0   0   0   1 175   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0 118   0   0   0   0   1   0   0   0]
 [  1   7   0   0   0   1   0   0   0 157   1   0   0   0   1   0   5]
 [  0   0   0   0   0   0   0   0   0   0 140   0   0   0   0   0   4]
 [  0   0   0   0   0   1   0   1   0   2   0  39   0   0   6   1   0]
 [  0   2   0   0   0   0   0   0   0   0   0   0 168   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 

Predicted  blca  brca  chol  coad  esca  hnsc  kich  kirc  lich  luad   ov  \
True                                                                         
blca        128     4     0     0     0     0     0     0     0     0    0   
brca          1   372     0     0     0     0     0     0     0     0    0   
chol          0     2    10     0     0     0     0     0     0     0    0   
coad          0     2     0   152     0     0     0     0     0     0    0   
esca         24     3     0     5    33     0     0     0     0     0    0   
hnsc          1     1     0     0     0   154     0     0     0     0    0   
kich          0     0     0     0     0     0    28     1     0     0    0   
kirc          1     1     0     0     0     0     1   175     0     0    0   
lich          0     0     0     0     1     0     0     0   118     0    0   
luad          1     7     0     0     0     1     0     0     0   157    1   
ov            0     0     0     0     0     0     0     0     0     0  140   
paad          0     0     0     0     0     1     0     1     0     2    0   
prad          0     2     0     0     0     0     0     0     0     0    0   
skcm          0     0     0     0     0     0     0     0     0     0    0   
stad          1     0     0     8     0     1     0     0     0     3    0   
thca          0     1     0     0     0     0     0     0     0     1    0   
ucec          0     7     0     0     0     0     0     0     0     1    0   
All         157   402    10   165    34   157    29   177   118   164  141   

Predicted  paad  prad  skcm  stad  thca  ucec   All  
True                                                 
blca          0     0     0     0     0     0   132  
brca          0     0     0     0     0     0   373  
chol          0     0     0     0     0     0    12  
coad          0     0     0     0     0     0   154  
esca          0     0     0     1     0     0    66  
hnsc          0     0     0     0     0     1   157  
kich          0     0     0     0     0     1    30  
kirc          0     0     0     0     0     0   178  
lich          0     0     1     0     0     0   120  
luad          0     0     0     1     0     5   173  
ov            0     0     0     0     0     4   144  
paad         39     0     0     6     1     0    50  
prad          0   168     0     0     0     0   170  
skcm          0     0   123     0     0     0   123  
stad          1     1     0   131     0     0   146  
thca          0     0     0     0   167     0   169  
ucec          0     0     0     0     0   171   179  
All          40   169   124   139   168   182  2376

In [21]:
from sklearn.neural_network import MLPClassifier 

clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf = clf.fit(train, r_train_labels)   

nnet_pred = clf.predict(test)

nnet_cm = confusion_matrix(r_test_labels, nnet_pred)
print(nnet_cm)

y_true = pd.Series(r_test_labels)
y_pred = pd.Series(nnet_pred)

pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

print("Accuracy: ", metrics.accuracy_score(r_test_labels, nnet_pred))

[[  0 132   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 373   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 154   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  66   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 157   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  30   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 178   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 120   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 173   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  50   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 170   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 123   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 

In [47]:
# model = tf.keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
# model.add(layers.Dense(64, activation='relu'))
# model.add(layers.Dense(64, activation='relu'))

# softmax with 17 output units; one for each class label 
# model.add(layers.Dense(17, activation='softmax'))

In [3]:
# One hot encoding for keras model 

from tensorflow.keras.utils import to_categorical
encoded_train = to_categorical(r_train_types)
encoded_test = to_categorical(r_test_types)


In [71]:
model = tf.keras.Sequential()

#model.add(layers.Dense(64, input_shape=(2403,)))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='sigmoid'))
model.add(layers.Dense(128, activation='sigmoid'))
model.add(layers.Dense(128, activation='sigmoid'))
# model.add(layers.Dense(128, activation='relu'))
# model.add(layers.Dense(128, activation='relu'))
# model.add(layers.Dense(64, activation='sigmoid'))

# softmax with 17 output units; one for each class label 
model.add(layers.Dense(17, activation='softmax'))

model.compile(optimizer=tf.train.RMSPropOptimizer(0.00005),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Epochs = 10 unless otherwise noted 
# Learning rate: 0.01 = ~40% 
# Learning rate: 0.001 = ~63%
# Learning rate: 0.007 = ~35% 
# Learning rate: 0.0009 = ~68% 
# Learning rate: 0.0005 = ~72%  // epochs = 50
# Learning rate: 0.0002 = ~73%  // epochs = 50
# Learning rate: 0.00009 = ~77% // epochs = 100
# Learning rate: 0.00009 = ~78% // epochs = 200

# setup model training 
# model.compile(optimizer=tf.train.AdamOptimizer(0.01),
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])
# Configure a model for categorical classification.
# model.compile(optimizer=tf.train.RMSPropOptimizer(0.01),
#               loss=tf.keras.losses.categorical_crossentropy,
#               metrics=[tf.keras.metrics.categorical_accuracy])

In [72]:

# train! 
# epochs is how many times you go through training set
# batch_size is the number of samples to propogate at once

model.fit(train, encoded_train, epochs=100, batch_size=32)


Epoch 1/100
5574/5574 [==============================] - 2s 385us/step - loss: 3.0002 - acc: 0.0513
Epoch 2/100
5574/5574 [==============================] - 1s 165us/step - loss: 2.7149 - acc: 0.1493
Epoch 3/100
5574/5574 [==============================] - 1s 167us/step - loss: 2.5774 - acc: 0.1512
Epoch 4/100
5574/5574 [==============================] - 1s 165us/step - loss: 2.4913 - acc: 0.1789
Epoch 5/100
5574/5574 [==============================] - 1s 174us/step - loss: 2.4182 - acc: 0.2580
Epoch 6/100
5574/5574 [==============================] - 1s 165us/step - loss: 2.3493 - acc: 0.2840
Epoch 7/100
5574/5574 [==============================] - 1s 168us/step - loss: 2.2819 - acc: 0.3082
Epoch 8/100
5574/5574 [==============================] - 1s 167us/step - loss: 2.2173 - acc: 0.3364
Epoch 9/100
5574/5574 [==============================] - 1s 168us/step - loss: 2.1563 - acc: 0.3645
Epoch 10/100
5574/5574 [==============================] - 1s 172us/step - loss: 2.0978 - acc: 0.3947

5574/5574 [==============================] - 1s 160us/step - loss: 0.9870 - acc: 0.7027
Epoch 83/100
5574/5574 [==============================] - 1s 171us/step - loss: 0.9817 - acc: 0.7047
Epoch 84/100
5574/5574 [==============================] - 1s 197us/step - loss: 0.9767 - acc: 0.7060
Epoch 85/100
5574/5574 [==============================] - 1s 208us/step - loss: 0.9746 - acc: 0.7052
Epoch 86/100
5574/5574 [==============================] - 1s 193us/step - loss: 0.9720 - acc: 0.7045
Epoch 87/100
5574/5574 [==============================] - 1s 173us/step - loss: 0.9675 - acc: 0.7078
Epoch 88/100
5574/5574 [==============================] - 1s 174us/step - loss: 0.9646 - acc: 0.7067
Epoch 89/100
5574/5574 [==============================] - 1s 163us/step - loss: 0.9625 - acc: 0.7099
Epoch 90/100
5574/5574 [==============================] - 1s 163us/step - loss: 0.9598 - acc: 0.7104
Epoch 91/100
5574/5574 [==============================] - 1s 168us/step - loss: 0.9584 - acc: 0.7101
Epo

In [68]:
ynew = model.predict_classes(test)


In [70]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

nnyhat = confusion_matrix(test_types, ynew)
print(nnyhat)
print("Accuracy: ", metrics.accuracy_score(r_test_types, ynew))
# for i in range(len(r_test_labels)):
#     print("X=%s, Predicted=%s" % (r_test_labels[i], ynew[i]))

y_true = pd.Series(r_test_labels)
y_pred = pd.Series(ynew)

pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

[[138   0   1   0   0   0   0   0   0   0   0   0   0   0   3   0   2]
 [  0  72   6   0   0   0  17   0   0   3   6   6  12   0   7   0   3]
 [  0   3 307   0   0   1   4   0   4   0  13   2   3   4  32   0   0]
 [  0   0   0   0   0   0   0   0   0   5   6   0   0   0   0   1   0]
 [  0   4   1   0 119   0   0   0   0   1   2   0  21   0   1   4   1]
 [  0  13   0   0   2  12  10   0   0   1   2   1  24   0   0   0   1]
 [  0  19   2   0   0   2 124   0   0   0   4   1   1   1   1   1   1]
 [  0   0   2   0   0   0   0  23   3   0   0   0   0   1   1   0   0]
 [  0   0   8   0   0   0   0   5 161   0   0   0   0   0   3   0   1]
 [  0   2   2   0   2   1   0   0   0  98   1   0   7   2   0   3   2]
 [  1  10  14   0   1   0   1   0   0   4 118   1   5   8   6   4   0]
 [  0   1   6   0   0   0   0   0   0   0   2 157   2   0   1   1   0]
 [  0   8   0   0  19   8   1   0   1   3   6   1  95   1   0   3   0]
 [  1   3   0   0   0   0   0   0   0   0   5   0   0 160   0   0   0]
 [  1 

Predicted    0    1    2    4   5    6   7    8    9   10   11   12   13   14  \
True                                                                            
blca         0   72    6    0   0   17   0    0    3    6    6   12    0    7   
brca         0    3  307    0   1    4   0    4    0   13    2    3    4   32   
chol         0    0    0    0   0    0   0    0    5    6    0    0    0    0   
coad         0    4    1  119   0    0   0    0    1    2    0   21    0    1   
esca         0   13    0    2  12   10   0    0    1    2    1   24    0    0   
hnsc         0   19    2    0   2  124   0    0    0    4    1    1    1    1   
kich         0    0    2    0   0    0  23    3    0    0    0    0    1    1   
kirc         0    0    8    0   0    0   5  161    0    0    0    0    0    3   
lich         0    2    2    2   1    0   0    0   98    1    0    7    2    0   
luad         1   10   14    1   0    1   0    0    4  118    1    5    8    6   
ov         138    0    1    0   0    0   0    0    0    0    0    0    0    3   
paad         0    2    1    1   0    0   1    0    0    9    0    6    0    0   
prad         0    1    6    0   0    0   0    0    0    2  157    2    0    1   
skcm         0    3    2    0   0    0   0    1    2    1    0    0    4    0   
stad         0    8    0   19   8    1   0    1    3    6    1   95    1    0   
thca         1    3    0    0   0    0   0    0    0    5    0    0  160    0   
ucec         1    5   22    1   0    1   0    3    0    1    2    0    0  141   
All        141  145  374  145  24  158  29  173  117  176  171  176  181  196   

Predicted  15   16   All  
True                      
blca        0    3   132  
brca        0    0   373  
chol        1    0    12  
coad        4    1   154  
esca        0    1    66  
hnsc        1    1   157  
kich        0    0    30  
kirc        0    1   178  
lich        3    2   120  
luad        4    0   173  
ov          0    2   144  
paad       30    0    50  
prad        1    0   170  
skcm        0  110   123  
stad        3    0   146  
thca        0    0   169  
ucec        0    2   179  
All        47  123  2376